### ISSUE TITLE
tokenization options

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/pepperModules-RSTModules#1]
Currently the RST importer does tokenization using the tokenizer module. However, in some scenarios, we will want to convert an RST document with exactly the same tokenization as some other annotation tool. Typically this will be done by making the RST raw data for annotation have spaces at the positions of the desired tokenization.

Because of this, it would be good to have an option to use 'space based tokenization' instead of the 'smarter' tokenizer, since the tokenizer sometimes splits tokens up that the user wanted to keep together. When 'space based tokenization' is on, the tokens are determined by white space between tokens, or if they are at the beginning/end of a segment (i.e. if an RST segment does not end in space and the next RST segment does not begin with a space, we can still assume that there is a token border between them.

**Comment by FlorianZipser** [comment]
A new tokenizer was created, which tokenizes a text along a given list of separators. This list can be customized via the property "simpleTokenize". The property "tokenize" then also must be set to true. A description can be found at:

https://github.com/korpling/pepperModules-RSTModules/tree/develop

This is part of the new Pepper snapshot:

https://korpling.german.hu-berlin.de/saltnpepper/repository/saltNpepper_full/SaltNPepper_2015.01.27-SNAPSHOT.zip
